import { auth } from "@/auth";
import { redirect } from "next/navigation";
import { getCachedUser, getCachedChannels } from "@/lib/data";
import FlashcardRoadmap from "@/components/dashboard/FlashcardRoadmap";
import { db } from "@/db";
import { ideaVault } from "@/db/schema";
import { eq, desc } from "drizzle-orm";

export const metadata = {
    title: "Idea Vault — GapTuber",
};

export default async function IdeaVaultPage({
    searchParams,
}: {
    searchParams: Promise<{ channelId?: string }>;
}) {
    const session = await auth();
    const { channelId: selectedId } = await searchParams;

    if (!session?.user?.email) {
        redirect("/auth/signin");
    }

    const user = await getCachedUser(session.user.email);
    if (!user) {
        redirect("/auth/signin");
    }

    const allChannels = await getCachedChannels(user.id);

    const activeChannel = selectedId
        ? allChannels.find((c) => c.id === selectedId) || allChannels[0]
        : allChannels[0];

    if (!activeChannel) {
        redirect("/onboarding");
    }

    // Fetch from the new ideaVault table (excluding temporary system-generated roadmap ideas)
    const vaultIdeasRaw = await db.query.ideaVault.findMany({
        where: (iv, { eq, and, ne }) => and(
            eq(iv.channelId, activeChannel.id),
            ne(iv.source, "system") // Filter out the 5 auto-generated roadmap ideas
        ),
        orderBy: (iv, { desc }) => [desc(iv.createdAt)]
    });

    const mappedVaultIdeas = vaultIdeasRaw.map(iv => ({
        title: iv.title,
        hook: iv.hook || "",
        format: iv.format || "",
        targetAudience: iv.targetAudience || "",
        whyItWorks: iv.whyItWorks || "",
        script: iv.script || "",
        estimatedViewPotential: iv.estimatedViewPotential as any,
        signalSource: iv.referenceId || iv.source,  // referenceId holds AI signal for system ideas
        description: iv.description || "",
        tags: iv.tags || [],
    }));

    // Map ideaVault statuses → component statuses (ready/filming/done)
    function toCardStatus(status: string): string {
        if (status === "launched") return "done";
        if (status === "filming" || status === "scripting" || status === "production") return "filming";
        return "ready"; // backlog or anything else
    }

    const mappedStatuses = vaultIdeasRaw.reduce((acc, iv, i) => {
        acc[String(i)] = toCardStatus(iv.status);
        return acc;
    }, {} as Record<string, string>);

    return (
        <div className="max-w-6xl mx-auto px-5 sm:px-8 py-10 fade-up">
            <div className="mb-8 border-b border-[#1e1e22] pb-6">
                <div className="inline-flex items-center gap-2 px-2 py-0.5 bg-[#1e1e22] text-zinc-400 rounded text-[10px] font-mono font-bold uppercase tracking-wider mb-3">
                    project_{activeChannel.name.replace(/\s+/g, '_').toLowerCase()}
                </div>
                <h1 className="text-3xl font-extrabold text-white tracking-tight">Idea Vault & Content Roadmap</h1>
                <p className="text-zinc-500 text-sm mt-2 max-w-xl">
                    Manage all your saved video ideas. You can push ideas generated by the AI bot or found through competitor scans directly to this roadmap.
                </p>
            </div>

            <FlashcardRoadmap
                key={`vault-${activeChannel.id}`}
                category={activeChannel.category ?? "General"}
                topic={activeChannel.topic ?? "YouTube Channel"}
                theme={activeChannel.brandingData ? (activeChannel.brandingData as { theme?: string }).theme ?? "tech" : "tech"}
                channelId={activeChannel.id}
                videoIdeas={mappedVaultIdeas}
                videoIdeaStatus={mappedStatuses}
                isVaultMode={true}
            />
        </div>
    );
}
