import type { ScanAnalytics } from "@/db/schema";

export const SCORING_VERSION = "2.1.0";

type ProvenanceInput = {
    source?: NonNullable<ScanAnalytics["provenance"]>["source"];
    competitorsRequested: number;
    competitorsResolved: number;
    videos: number;
    comments: number;
    searchResults: number;
    dataConfidence: number;
};

/**
 * Describes exactly what a scan used. This metadata is deliberately generated by
 * the server rather than the language model so it cannot be invented or altered.
 */
export function buildAnalysisProvenance(input: ProvenanceInput): NonNullable<ScanAnalytics["provenance"]> {
    return {
        source: input.source ?? "YouTube Data API v3",
        generatedAt: new Date().toISOString(),
        cacheMaxAgeMinutes: 60,
        scoringVersion: SCORING_VERSION,
        dataConfidence: Math.round(Math.min(1, Math.max(0, input.dataConfidence)) * 100),
        sample: {
            competitorsRequested: input.competitorsRequested,
            competitorsResolved: input.competitorsResolved,
            videos: input.videos,
            comments: input.comments,
            searchResults: input.searchResults,
        },
        aiRole: "AI drafts titles, hooks, and outlines. Scores and evidence links are computed and validated by the server.",
        limitations: [
            "Public YouTube data cannot reveal impressions, click-through rate, retention, or private revenue.",
            "Search results are a point-in-time relevance sample, not YouTube search-volume data.",
            "Publishing-time and revenue figures are scenarios, not guaranteed forecasts.",
        ],
    };
}
